-- Fixture del contrato externo.
CREATE SCHEMA IF NOT EXISTS bookingnow;
CREATE TABLE IF NOT EXISTS bookingnow.correos_registrados (
    correo varchar(255) PRIMARY KEY,
    tipo varchar(16) NOT NULL CHECK (tipo IN ('CLIENTE','PROVEEDOR','ADMINISTRADOR'))
);
CREATE TABLE IF NOT EXISTS bookingnow.clientes (
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo varchar(255) NOT NULL UNIQUE,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    contrasena_hash varchar(255) NOT NULL,
    estado varchar(16) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','INACTIVA','BLOQUEADA'))
);
CREATE TABLE IF NOT EXISTS bookingnow.proveedores (
    id_proveedor bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo varchar(255) NOT NULL UNIQUE,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    contrasena_hash varchar(255) NOT NULL,
    estado varchar(16) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','INACTIVA','BLOQUEADA')),
    razon_social varchar(255) NOT NULL,
    razon_social_normalizada varchar(255) NOT NULL UNIQUE,
    nit varchar(11) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS bookingnow.usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo varchar(255) NOT NULL UNIQUE,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    contrasena_hash varchar(255) NOT NULL,
    rol varchar(32) NOT NULL CHECK (rol IN ('ADMINISTRADOR')),
    estado varchar(16) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','INACTIVA','BLOQUEADA'))
);
CREATE TABLE IF NOT EXISTS bookingnow.negocios (
    id_negocio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor bigint NOT NULL UNIQUE REFERENCES bookingnow.proveedores(id_proveedor),
    nombre varchar(255) NOT NULL,
    correo varchar(255) NOT NULL,
    num_contacto varchar(25) NOT NULL,
    direccion varchar(500),
    categoria varchar(100) NOT NULL,
    modalidad_virtual boolean NOT NULL,
    foto_principal varchar(2048),
    fecha_registro timestamp with time zone NOT NULL,
    CHECK (modalidad_virtual OR (direccion IS NOT NULL AND length(trim(direccion)) > 0))
);
CREATE TABLE IF NOT EXISTS bookingnow.negocio_multimedia (
    id_negocio bigint NOT NULL REFERENCES bookingnow.negocios(id_negocio),
    url varchar(2048) NOT NULL,
    tipo varchar(16) NOT NULL CHECK (tipo IN ('IMAGEN','VIDEO')),
    orden integer NOT NULL,
    PRIMARY KEY (id_negocio, orden)
);
CREATE TABLE IF NOT EXISTS bookingnow.servicios (
    id_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_negocio bigint NOT NULL REFERENCES bookingnow.negocios(id_negocio),
    nombre varchar(255) NOT NULL,
    duracion_minutos integer NOT NULL CHECK (duracion_minutos > 0),
    precio numeric(12,2) NOT NULL CHECK (precio >= 0),
    descripcion varchar(2000) NOT NULL,
    imagen_referencia varchar(2048),
    estado varchar(16) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);
