-- Contrato externo para pruebas; no ejecuta migraciones en Supabase.
CREATE SCHEMA IF NOT EXISTS bookingnow;
CREATE TABLE IF NOT EXISTS bookingnow.clientes (
    id_cliente bigint generated by default as identity primary key,
    correo varchar(255) not null,
    nombre_usuario varchar(50) not null unique,
    contrasena_hash varchar(255) not null
);
CREATE TABLE IF NOT EXISTS bookingnow.proveedores (
    id_proveedor bigint generated by default as identity primary key,
    correo varchar(255) not null,
    nombre_usuario varchar(50) not null unique,
    contrasena_hash varchar(255) not null,
    razon_social varchar(255) not null,
    nit varchar(255) not null
);
