-- Inicializa datos de desarrollo. No usar estas credenciales en producción.
-- Ejecutar en Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

ALTER TABLE bookingnow.correos_registrados
    DROP CONSTRAINT IF EXISTS correos_registrados_tipo_check;
ALTER TABLE bookingnow.correos_registrados
    ADD CONSTRAINT correos_registrados_tipo_check
    CHECK (tipo IN ('CLIENTE', 'PROVEEDOR', 'ADMINISTRADOR'));

CREATE TABLE IF NOT EXISTS bookingnow.usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo varchar(255) NOT NULL UNIQUE,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    contrasena_hash varchar(255) NOT NULL,
    rol varchar(32) NOT NULL CHECK (rol IN ('ADMINISTRADOR')),
    estado varchar(16) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA'))
);
ALTER TABLE bookingnow.usuarios ENABLE ROW LEVEL SECURITY;

-- Credenciales de desarrollo:
--   Administrador: admin@bookingnow.local / AdminDemo123!
--   Cliente: cliente.demo@bookingnow.local / ClienteDemo123!
--   Proveedor: proveedor.demo@bookingnow.local / ProveedorDemo123!
-- El hash BCrypt se genera en PostgreSQL; ninguna contraseña se almacena en texto plano.
INSERT INTO bookingnow.usuarios (correo, nombre_usuario, contrasena_hash, rol, estado)
VALUES ('admin@bookingnow.local', 'admin', extensions.crypt('AdminDemo123!', extensions.gen_salt('bf', 12)), 'ADMINISTRADOR', 'ACTIVA')
ON CONFLICT (correo) DO UPDATE
SET nombre_usuario = EXCLUDED.nombre_usuario,
    contrasena_hash = EXCLUDED.contrasena_hash,
    rol = EXCLUDED.rol,
    estado = EXCLUDED.estado;

INSERT INTO bookingnow.clientes (correo, nombre_usuario, contrasena_hash, estado)
VALUES ('cliente.demo@bookingnow.local', 'cliente_demo', extensions.crypt('ClienteDemo123!', extensions.gen_salt('bf', 12)), 'ACTIVA')
ON CONFLICT (correo) DO NOTHING;

INSERT INTO bookingnow.proveedores (correo, nombre_usuario, contrasena_hash, estado, razon_social, razon_social_normalizada, nit)
VALUES ('proveedor.demo@bookingnow.local', 'proveedor_demo', extensions.crypt('ProveedorDemo123!', extensions.gen_salt('bf', 12)), 'ACTIVA',
        'Proveedor Demo SAS', 'proveedor demo sas', '900765432-1')
ON CONFLICT (correo) DO NOTHING;

INSERT INTO bookingnow.correos_registrados (correo, tipo)
SELECT correo, 'ADMINISTRADOR' FROM bookingnow.usuarios WHERE correo = 'admin@bookingnow.local'
ON CONFLICT (correo) DO UPDATE SET tipo = EXCLUDED.tipo;
INSERT INTO bookingnow.correos_registrados (correo, tipo)
SELECT correo, 'CLIENTE' FROM bookingnow.clientes WHERE correo = 'cliente.demo@bookingnow.local'
ON CONFLICT (correo) DO NOTHING;
INSERT INTO bookingnow.correos_registrados (correo, tipo)
SELECT correo, 'PROVEEDOR' FROM bookingnow.proveedores WHERE correo = 'proveedor.demo@bookingnow.local'
ON CONFLICT (correo) DO NOTHING;

INSERT INTO bookingnow.negocios (id_proveedor, nombre, correo, num_contacto, direccion, categoria, modalidad_virtual, foto_principal, fecha_registro)
SELECT p.id_proveedor, 'Negocio Demo', 'negocio.demo@bookingnow.local', '+57 3001234567',
       'Calle 10 # 20-30, Medellín', 'Bienestar', false, 'https://images.example.com/negocio-demo.jpg', CURRENT_TIMESTAMP
FROM bookingnow.proveedores p
WHERE p.correo = 'proveedor.demo@bookingnow.local'
ON CONFLICT (id_proveedor) DO NOTHING;

INSERT INTO bookingnow.negocio_multimedia (id_negocio, url, tipo, orden)
SELECT n.id_negocio, 'https://images.example.com/negocio-demo-1.jpg', 'IMAGEN', 0
FROM bookingnow.negocios n
JOIN bookingnow.proveedores p ON p.id_proveedor = n.id_proveedor
WHERE p.correo = 'proveedor.demo@bookingnow.local'
ON CONFLICT (id_negocio, orden) DO NOTHING;
INSERT INTO bookingnow.negocio_multimedia (id_negocio, url, tipo, orden)
SELECT n.id_negocio, 'https://images.example.com/negocio-demo-video.mp4', 'VIDEO', 1
FROM bookingnow.negocios n
JOIN bookingnow.proveedores p ON p.id_proveedor = n.id_proveedor
WHERE p.correo = 'proveedor.demo@bookingnow.local'
ON CONFLICT (id_negocio, orden) DO NOTHING;

INSERT INTO bookingnow.servicios (id_negocio, nombre, duracion_minutos, precio, descripcion, imagen_referencia, estado, fecha_registro)
SELECT n.id_negocio, 'Asesoría inicial', 30, 25000.00, 'Sesión inicial de asesoría.',
       'https://images.example.com/asesoria-inicial.jpg', 'ACTIVO', CURRENT_TIMESTAMP
FROM bookingnow.negocios n
JOIN bookingnow.proveedores p ON p.id_proveedor = n.id_proveedor
WHERE p.correo = 'proveedor.demo@bookingnow.local'
  AND NOT EXISTS (SELECT 1 FROM bookingnow.servicios s WHERE s.id_negocio = n.id_negocio AND s.nombre = 'Asesoría inicial');

-- Consulta de comprobación: debe devolver datos en las seis entidades.
SELECT 'usuarios' AS entidad, count(*) AS registros FROM bookingnow.usuarios
UNION ALL SELECT 'clientes', count(*) FROM bookingnow.clientes
UNION ALL SELECT 'proveedores', count(*) FROM bookingnow.proveedores
UNION ALL SELECT 'negocios', count(*) FROM bookingnow.negocios
UNION ALL SELECT 'negocio_multimedia', count(*) FROM bookingnow.negocio_multimedia
UNION ALL SELECT 'servicios', count(*) FROM bookingnow.servicios;

-- Debe devolver una fila con tipo y rol ADMINISTRADOR, estado ACTIVA y hash_bcrypt=true.
SELECT u.correo, c.tipo, u.rol, u.estado, (u.contrasena_hash LIKE '$2%') AS hash_bcrypt
FROM bookingnow.usuarios u
JOIN bookingnow.correos_registrados c ON c.correo = u.correo
WHERE u.correo = 'admin@bookingnow.local';
